### ISSUE TITLE
Upgrade documentation from v0.9 to v1.0

### ISSUE THREAD

**Issue by yomguy** [Ircam-WAM/TimeSide#121]
The doctests should be removed and pushed to some notebooks so that the runner is not needed to generate the doc.
The new doc will be published on readthedocs. See readthedocs.yml.

**Comment by Tointoin** [comment]
- [ ] Dummy Plugin Example(s) (@yomguy )
- [ ] API doc from OpenAPI schema (@Tointoin )
- [ ] Create items from Deezer/Youtube audios (@Tointoin )
- [ ] Run dummy Plugin on items (@Tointoin )
   - [ ] from django admin shell
   - [ ] through DRF API
- [ ] Import/Export Database (@Tointoin & @yomguy )
- [ ] Timeside instance deployment (@Tointoin & @yomguy )

**Comment by Tointoin** [comment]
> The new doc will be published on readthedocs. See readthedocs.yml.
On which branch is readthedocs.yml?

**Comment by yomguy** [comment]
> > The new doc will be published on readthedocs. See readthedocs.yml.
> 
> On which branch is readthedocs.yml?

`latest` is the master branch
`stable` is the last tagged version
