### ISSUE TITLE
Add websocket/redis node.js server

### ISSUE THREAD

**Issue by clementgerard1** [Ircam-WAM/TimeSide#245]
Add node.js express socket.io server
Connection with redis
Use django rest api token for auth to websocket
Listen redis messages :
- progress : id, pourcent
- complete : id
- fail : id
- pending : id

**Comment by yomguy** [comment]
@clementgerard1 we have a privilege pb at runtime:
```
websockets_1  | > websockets@0.0.1 dev
websockets_1  | > npm install && babel-watch server.js
websockets_1  | 
websockets_1  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
websockets_1  |   errno: -13,
websockets_1  |   code: 'EACCES',
websockets_1  |   syscall: 'scandir',
websockets_1  |   path: '/root/.npm/_logs'
websockets_1  | }
```
Trying `USER root` in websockets/Dockerfile doesn't fix it.
