### ISSUE TITLE
Prevent GStreamer from hijacking --help

### ISSUE THREAD

**Issue by thomasfillon** [Ircam-WAM/TimeSide#87]
Gstreamer is overriding command line help message.

This issue has already been circumvented in the `timeside-launch` script see https://github.com/Parisson/TimeSide/blob/6bc2813a9bfb0e241b87e43925591b17d02597ad/scripts/timeside-launch#L141
but it also appears with django management commands as indicated below.

```
$ python manage.py timeside-create-boilerplate --help
 Usage:
    manage.py [OPTION...] - GStreamer initialization

  Help Options:
    -h, --help                        Show help options
   --help-all                        Show all help options
    --help-gst                        Show GStreamer Options
```

In this case the same workaround is not obvious to implement.

See 
- https://bugzilla.gnome.org/show_bug.cgi?id=425847
- https://bugzilla.gnome.org/show_bug.cgi?id=549879
- https://github.com/mopidy/mopidy/issues/95
- https://github.com/docopt/docopt/issues/245

**Comment by yomguy** [comment]
Closed as aubio based processors are preferred by default.
