### ISSUE TITLE
Refactorization of Analyzer Parameters

### ISSUE THREAD

**Issue by thomasfillon** [Ircam-WAM/TimeSide#92]
Currently Analyzer parameters specification and validation is based on [Enthought Traits](http://code.enthought.com/projects/traits/) the [Traitlets](https://traitlets.readthedocs.io/en/stable/) framework that seems to be derived from Traits may be simpler to use.

Nevertheless with the new web API and the new JavaScript player parameters serialization and validation needs are evolving and neither Traits or Traitlets may be appropriate or would require a lot of extra work.

Some interresting Data Validation tools are listed [here](http://awesome-python.com/#data-validation).

[JSON SCHEMA](http://json-schema.org) may be very appropriate.

**Comment by yomguy** [comment]
Sure if you think Traitlets is better. 
Hoping the integration of E. Traits is a good pre-figuration for this, can you evaluate the amount of work for this task?

**Comment by yomguy** [comment]
finalized in a186a66f
